### ISSUE TITLE
AssertionError: torch.Size in compute_iou

### ISSUE THREAD

**Issue by Vadim2S** [NoelShin/selfmask#1]
I am try test DUTS or ECSSD with pre-trained weight. Result always the same. ~2x difference in tensor size. 

 ious = compute_iou(pred_mask=pred_mask, gt_mask=gt_mask)
  File "e:\_Vadim_Work\selfmask\metrics\iou.py", line 19, in compute_iou
    assert pred_mask.shape == gt_mask.shape, f"{pred_mask.shape} != {gt_mask.shape}"
AssertionError: torch.Size([20, 152, 200]) != torch.Size([20, 302, 400])

**Comment by noelshin** [comment]
Hi, thanks for the enquiry!

Are you using evaluator.py?
If so, I can confirm it doesn't raise the same assertion error on my side.
Could you please provide the image file name that raises the error?

**Comment by Vadim2S** [comment]
Sorry! My mistake. I was am confused by "clustering" name of config section and set scale to 1 along with GPU off.
