### ISSUE TITLE
salient mask selection

### ISSUE THREAD

**Issue by ruoshuichengyang** [NoelShin/selfmask#3]
Hello sir, if I want to train my own data,  how can I get salient mask?How can I do offline spectral clustering to obtain candidate set?

**Comment by noelshin** [comment]
Hello @ruoshuichengyang, I'm sorry for the very late response.

(1) I'll try to upload a script for computing a salient mask with your own images.
(2) You can use "mask_generator.py" file (https://github.com/NoelShin/selfmask/blob/master/datasets/mask_generator.py) to obtain a candidate set.

I'll leave another comment here once done.

Sorry again for the late reply and thank you for your interest in our work.

**Comment by noelshin** [comment]
A python script for generating pseudo-masks with your own images is added. Please use this file (https://github.com/NoelShin/selfmask/blob/master/mask_generator.py). You just need to set a list of image file paths.

Please let me know if you encounter any issues. :)
