### ISSUE TITLE
voting strategy

### ISSUE THREAD

**Issue by lin-902** [NoelShin/selfmask#4]
Hello, I want to train with my own dataset. I've used mask_generator.py to generate pseudo_masks for different networks. How do I use the voting strategy to generate a salient mask, is there a source code? Thank you so much.

**Comment by noelshin** [comment]
Hello, @lin-902! Thank you very much for your interest in our work - I'll try to find a time to make a script for that and will leave another comment once done.

**Comment by noelshin** [comment]
A python script for generating pseudo-masks with your own images is added. Please use this file (https://github.com/NoelShin/selfmask/blob/master/mask_generator.py). You just need to set a list of image file paths.

Please let me know if you encounter any issues. :)
