### ISSUE TITLE
About pre-trained weights

### ISSUE THREAD

**Issue by YeeZ93** [NoelShin/selfmask#6]
Hi, thanks so much for the work!

However I can not download the pre-trained weights with the given links on this project page. Could you please check and update the links?

Thanks in advance!

Best,
Jun-Pu

**Comment by noelshin** [comment]
Hi @ZHANG-Jun-Pu! Thank you for your inquiry. I just checked and I could download the weights through the links. (I checked using Safari.) If it doesn't work with a web browser you're using, you can try to download it in your terminal by using `curl` or `wget` command. For instance, type the following line in your terminal

`curl -o selfmask_nq10.pt https://www.robots.ox.ac.uk/\~vgg/research/selfmask/shared_files/selfmask_nq10.pt
`
or 
`wget https://www.robots.ox.ac.uk/\~vgg/research/selfmask/shared_files/selfmask_nq10.pt`

Let me know if it doesn't work.

Kind regards,
noel

**Comment by YeeZ93** [comment]
Hi, thanks for the quick reply! The links are ok with Safari. Thanks!

Best,
Jun-Pu
