### ISSUE TITLE
How to use on custom datasets？

### ISSUE THREAD

**Issue by HalvesChen** [NoelShin/selfmask#7]
Hello！
I want to use this method on custom datasets, but I don't know how to get pseudo mask.
Could you give me help?

**Comment by noelshin** [comment]
Dear @chendaozai 

Thank you for reaching out and your interest in our work - you can check `mask_generator.py` to generate pseudo-masks with your images. You just need to set a list of image paths in the script and save the resulting file if necessary.

Kind regards,
Noel
